// flow-typed signature: 867828d964f571d0a22b6c7923785727
// flow-typed version: 0.4.20

// This is an autogenerated libdef stub for the 'apollo-client' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'apollo-client' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'apollo-client' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'apollo-client/actions' {
  declare module.exports: any;
}

declare module 'apollo-client/afterware' {
  declare module.exports: any;
}

declare module 'apollo-client/batchedNetworkInterface' {
  declare module.exports: any;
}

declare module 'apollo-client/batching' {
  declare module.exports: any;
}

declare module 'apollo-client/batching/queryMerging' {
  declare module.exports: any;
}

declare module 'apollo-client/data/diffAgainstStore' {
  declare module.exports: any;
}

declare module 'apollo-client/data/extensions' {
  declare module.exports: any;
}

declare module 'apollo-client/data/mutationResults' {
  declare module.exports: any;
}

declare module 'apollo-client/data/readFromStore' {
  declare module.exports: any;
}

declare module 'apollo-client/data/replaceQueryResults' {
  declare module.exports: any;
}

declare module 'apollo-client/data/scopeQuery' {
  declare module.exports: any;
}

declare module 'apollo-client/data/store' {
  declare module.exports: any;
}

declare module 'apollo-client/data/storeUtils' {
  declare module.exports: any;
}

declare module 'apollo-client/data/writeToStore' {
  declare module.exports: any;
}

declare module 'apollo-client/errors' {
  declare module.exports: any;
}

declare module 'apollo-client/index' {
  declare module.exports: any;
}

declare module 'apollo-client/middleware' {
  declare module.exports: any;
}

declare module 'apollo-client/mutations/store' {
  declare module.exports: any;
}

declare module 'apollo-client/networkInterface' {
  declare module.exports: any;
}

declare module 'apollo-client/ObservableQuery' {
  declare module.exports: any;
}

declare module 'apollo-client/optimistic-data/store' {
  declare module.exports: any;
}

declare module 'apollo-client/queries/directives' {
  declare module.exports: any;
}

declare module 'apollo-client/queries/getFromAST' {
  declare module.exports: any;
}

declare module 'apollo-client/queries/queryTransform' {
  declare module.exports: any;
}

declare module 'apollo-client/queries/store' {
  declare module.exports: any;
}

declare module 'apollo-client/QueryManager' {
  declare module.exports: any;
}

declare module 'apollo-client/queryPrinting' {
  declare module.exports: any;
}

declare module 'apollo-client/scheduler' {
  declare module.exports: any;
}

declare module 'apollo-client/store' {
  declare module.exports: any;
}

declare module 'apollo-client/util/errorHandling' {
  declare module.exports: any;
}

declare module 'apollo-client/util/Observable' {
  declare module.exports: any;
}

declare module 'apollo-client/watchQueryOptions' {
  declare module.exports: any;
}

