// flow-typed signature: a285b29e9d7bffa7d52ef368f565313a
// flow-typed version: 6.16.0

// This is an autogenerated libdef stub for the 'babel-polyfill' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'babel-polyfill' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'babel-polyfill' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'babel-polyfill/browser' {
  declare module.exports: any;
}

declare module 'babel-polyfill/dist/polyfill' {
  declare module.exports: any;
}

declare module 'babel-polyfill/dist/polyfill.min' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/index' {
  declare module.exports: any;
}

declare module 'babel-polyfill/scripts/postpublish' {
  declare module.exports: any;
}

declare module 'babel-polyfill/scripts/prepublish' {
  declare module.exports: any;
}

