// flow-typed signature: a030ff9758a55d8814de0698d67159e3
// flow-typed version: 3.1.0

// This is an autogenerated libdef stub for the 'connect-redis' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'connect-redis' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'connect-redis' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'connect-redis/bench/redisbench' {
  declare module.exports: any;
}

declare module 'connect-redis/index' {
  declare module.exports: any;
}

declare module 'connect-redis/lib/connect-redis' {
  declare module.exports: any;
}

declare module 'connect-redis/test/connect-redis-test' {
  declare module.exports: any;
}

declare module 'connect-redis/test/redis-server' {
  declare module.exports: any;
}

