// flow-typed signature: 50882a2b75018c7d7848e7c859b322a5
// flow-typed version: 1.14.1

// This is an autogenerated libdef stub for the 'express-session' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'express-session' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'express-session' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'express-session/index' {
  declare module.exports: any;
}

declare module 'express-session/session/cookie' {
  declare module.exports: any;
}

declare module 'express-session/session/memory' {
  declare module.exports: any;
}

declare module 'express-session/session/session' {
  declare module.exports: any;
}

declare module 'express-session/session/store' {
  declare module.exports: any;
}

