// flow-typed signature: 4a3f3b3d11f85005fffd79b0e5385e44
// flow-typed version: 1.3.0

// This is an autogenerated libdef stub for the 'express-error-middleware' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'express-error-middleware' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'express-error-middleware' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'express-error-middleware/lib/errors' {
  declare module.exports: any;
}

declare module 'express-error-middleware/lib/index' {
  declare module.exports: any;
}

declare module 'express-error-middleware/test/app' {
  declare module.exports: any;
}

declare module 'express-error-middleware/test/errors' {
  declare module.exports: any;
}

declare module 'express-error-middleware/test/middleware-test' {
  declare module.exports: any;
}

