// flow-typed signature: 9d6bb4faf258b945c11e59763eb9d73d
// flow-typed version: 4.14.0

// This is an autogenerated libdef stub for the 'express' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'express' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'express' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'express/index' {
  declare module.exports: any;
}

declare module 'express/lib/application' {
  declare module.exports: any;
}

declare module 'express/lib/express' {
  declare module.exports: any;
}

declare module 'express/lib/middleware/init' {
  declare module.exports: any;
}

declare module 'express/lib/middleware/query' {
  declare module.exports: any;
}

declare module 'express/lib/request' {
  declare module.exports: any;
}

declare module 'express/lib/response' {
  declare module.exports: any;
}

declare module 'express/lib/router/index' {
  declare module.exports: any;
}

declare module 'express/lib/router/layer' {
  declare module.exports: any;
}

declare module 'express/lib/router/route' {
  declare module.exports: any;
}

declare module 'express/lib/utils' {
  declare module.exports: any;
}

declare module 'express/lib/view' {
  declare module.exports: any;
}

