// flow-typed signature: 2b88efbb19d070ab7e097ec360e0a0b5
// flow-typed version: 0.5.4

// This is an autogenerated libdef stub for the 'express-graphql' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'express-graphql' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'express-graphql' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'express-graphql/dist/index' {
  declare module.exports: any;
}

declare module 'express-graphql/dist/parseBody' {
  declare module.exports: any;
}

declare module 'express-graphql/dist/renderGraphiQL' {
  declare module.exports: any;
}

