// flow-typed signature: 61cec90017f72e29b4716816dc070693
// flow-typed version: 0.1.14

// This is an autogenerated libdef stub for the 'graphql-tag' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'graphql-tag' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'graphql-tag' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'graphql-tag/index' {
  declare module.exports: any;
}

declare module 'graphql-tag/parser' {
  declare module.exports: any;
}

declare module 'graphql-tag/printer' {
  declare module.exports: any;
}

