// flow-typed signature: fbdf92a1799eee1dc7fb703974d8bf37
// flow-typed version: 2.4.0

// This is an autogenerated libdef stub for the 'ioredis' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'ioredis' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'ioredis' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'ioredis/benchmarks/single_node' {
  declare module.exports: any;
}

declare module 'ioredis/examples/basic_operations' {
  declare module.exports: any;
}

declare module 'ioredis/index' {
  declare module.exports: any;
}

declare module 'ioredis/lib/cluster/connection_pool' {
  declare module.exports: any;
}

declare module 'ioredis/lib/cluster/delay_queue' {
  declare module.exports: any;
}

declare module 'ioredis/lib/cluster/index' {
  declare module.exports: any;
}

declare module 'ioredis/lib/command' {
  declare module.exports: any;
}

declare module 'ioredis/lib/commander' {
  declare module.exports: any;
}

declare module 'ioredis/lib/connectors/connector' {
  declare module.exports: any;
}

declare module 'ioredis/lib/connectors/sentinel_connector' {
  declare module.exports: any;
}

declare module 'ioredis/lib/pipeline' {
  declare module.exports: any;
}

declare module 'ioredis/lib/redis' {
  declare module.exports: any;
}

declare module 'ioredis/lib/redis/event_handler' {
  declare module.exports: any;
}

declare module 'ioredis/lib/redis/parser' {
  declare module.exports: any;
}

declare module 'ioredis/lib/reply_error' {
  declare module.exports: any;
}

declare module 'ioredis/lib/scan_stream' {
  declare module.exports: any;
}

declare module 'ioredis/lib/script' {
  declare module.exports: any;
}

declare module 'ioredis/lib/subscription_set' {
  declare module.exports: any;
}

declare module 'ioredis/lib/transaction' {
  declare module.exports: any;
}

declare module 'ioredis/lib/utils/index' {
  declare module.exports: any;
}

declare module 'ioredis/test_sentinel' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/auth' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/cluster' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/connection' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/drop_buffer_support' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/exports' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/fatal_error' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/lazy_connect' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/monitor' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/pipeline' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/pub_sub' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/ready_check' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/reconnect_on_error' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/scan_stream' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/scripting' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/select' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/send_command' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/sentinel' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/show_friendly_error_stack' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/string_numbers' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/transaction' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/transformer' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/watch-exec' {
  declare module.exports: any;
}

declare module 'ioredis/test/helpers/global' {
  declare module.exports: any;
}

declare module 'ioredis/test/helpers/mock_server' {
  declare module.exports: any;
}

declare module 'ioredis/test/unit/cluster' {
  declare module.exports: any;
}

declare module 'ioredis/test/unit/command' {
  declare module.exports: any;
}

declare module 'ioredis/test/unit/commander' {
  declare module.exports: any;
}

declare module 'ioredis/test/unit/connectors/connector' {
  declare module.exports: any;
}

declare module 'ioredis/test/unit/index' {
  declare module.exports: any;
}

declare module 'ioredis/test/unit/redis' {
  declare module.exports: any;
}

declare module 'ioredis/test/unit/utils' {
  declare module.exports: any;
}

