// flow-typed signature: 456a9ece854f8a9115a9d318600a5bbc
// flow-typed version: 1.1.0

// This is an autogenerated libdef stub for the 'passport-github' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'passport-github' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'passport-github' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'passport-github/lib/errors/apierror' {
  declare module.exports: any;
}

declare module 'passport-github/lib/index' {
  declare module.exports: any;
}

declare module 'passport-github/lib/profile' {
  declare module.exports: any;
}

declare module 'passport-github/lib/strategy' {
  declare module.exports: any;
}

