// flow-typed signature: 4a3e78ff8780a37d8bb95eee98100cdf
// flow-typed version: 0.3.2

// This is an autogenerated libdef stub for the 'passport' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'passport' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'passport' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'passport/lib/authenticator' {
  declare module.exports: any;
}

declare module 'passport/lib/errors/authenticationerror' {
  declare module.exports: any;
}

declare module 'passport/lib/framework/connect' {
  declare module.exports: any;
}

declare module 'passport/lib/http/request' {
  declare module.exports: any;
}

declare module 'passport/lib/index' {
  declare module.exports: any;
}

declare module 'passport/lib/middleware/authenticate' {
  declare module.exports: any;
}

declare module 'passport/lib/middleware/initialize' {
  declare module.exports: any;
}

declare module 'passport/lib/strategies/session' {
  declare module.exports: any;
}

