// flow-typed signature: 3f4c65daa8d2d25904adb5ef7ad7d904
// flow-typed version: 4.0.0-alpha.4

// This is an autogenerated libdef stub for the 'react-router' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'react-router' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'react-router' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'react-router/BrowserRouter' {
  declare module.exports: any;
}

declare module 'react-router/createServerRenderContext' {
  declare module.exports: any;
}

declare module 'react-router/HashRouter' {
  declare module.exports: any;
}

declare module 'react-router/index' {
  declare module.exports: any;
}

declare module 'react-router/karma.conf' {
  declare module.exports: any;
}

declare module 'react-router/Link' {
  declare module.exports: any;
}

declare module 'react-router/locationBroadcast' {
  declare module.exports: any;
}

declare module 'react-router/LocationUtils' {
  declare module.exports: any;
}

declare module 'react-router/Match' {
  declare module.exports: any;
}

declare module 'react-router/matchPattern' {
  declare module.exports: any;
}

declare module 'react-router/MatchProvider' {
  declare module.exports: any;
}

declare module 'react-router/MemoryRouter' {
  declare module.exports: any;
}

declare module 'react-router/Miss' {
  declare module.exports: any;
}

declare module 'react-router/NavigationPrompt' {
  declare module.exports: any;
}

declare module 'react-router/PropTypes' {
  declare module.exports: any;
}

declare module 'react-router/Redirect' {
  declare module.exports: any;
}

declare module 'react-router/ServerRouter' {
  declare module.exports: any;
}

declare module 'react-router/StaticRouter' {
  declare module.exports: any;
}

declare module 'react-router/tests.webpack' {
  declare module.exports: any;
}

declare module 'react-router/umd/react-router' {
  declare module.exports: any;
}

declare module 'react-router/umd/react-router.min' {
  declare module.exports: any;
}

declare module 'react-router/webpack.config' {
  declare module.exports: any;
}

