// flow-typed signature: d8f8ea500df5f1626f32ab6490d7d15b
// flow-typed version: 0.5.7

// This is an autogenerated libdef stub for the 'react-apollo' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'react-apollo' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'react-apollo' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'react-apollo/ApolloProvider' {
  declare module.exports: any;
}

declare module 'react-apollo/dist/index' {
  declare module.exports: any;
}

declare module 'react-apollo/dist/index.min' {
  declare module.exports: any;
}

declare module 'react-apollo/graphql' {
  declare module.exports: any;
}

declare module 'react-apollo/index' {
  declare module.exports: any;
}

declare module 'react-apollo/parser' {
  declare module.exports: any;
}

declare module 'react-apollo/preprocessor' {
  declare module.exports: any;
}

declare module 'react-apollo/scripts/filesize' {
  declare module.exports: any;
}

declare module 'react-apollo/server' {
  declare module.exports: any;
}

declare module 'react-apollo/shallowEqual' {
  declare module.exports: any;
}

