// flow-typed signature: d34841638314e714808a1f67c2cf42f1
// flow-typed version: <<STUB>>/styled-components_v1.0.8/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components' {
  declare module.exports: (element: string) => (css: string) => ReactClass<*>;
}
