// flow-typed signature: 93deec4faab1b13ae11a20335ae56de3
// flow-typed version: 2.0.0

// This is an autogenerated libdef stub for the 'supertest' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'supertest' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'supertest' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'supertest/index' {
  declare module.exports: any;
}

declare module 'supertest/lib/agent' {
  declare module.exports: any;
}

declare module 'supertest/lib/test' {
  declare module.exports: any;
}

declare module 'supertest/test/supertest' {
  declare module.exports: any;
}

