// flow-typed signature: 8a3122fed911434ef5c89f654b275341
// flow-typed version: 2.12.2

// This is an autogenerated libdef stub for the 'webpack-hot-middleware' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'webpack-hot-middleware' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'webpack-hot-middleware' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'webpack-hot-middleware/client-overlay' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/client' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/example/client' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/example/extra' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/example/server' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/example/webpack.config' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/example/webpack.config.multientry' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/helpers' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/middleware' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/process-update' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/test/client-test' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/test/helpers-test' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/test/middleware-test' {
  declare module.exports: any;
}

