// flow-typed signature: fd83d7887b6c4fc89f9e5c5495e88719
// flow-typed version: 2.1.0-beta.25

// This is an autogenerated libdef stub for the 'webpack' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'webpack' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'webpack' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'webpack/bin/config-optimist' {
  declare module.exports: any;
}

declare module 'webpack/bin/config-yargs' {
  declare module.exports: any;
}

declare module 'webpack/bin/convert-argv' {
  declare module.exports: any;
}

declare module 'webpack/bin/webpack' {
  declare module.exports: any;
}

declare module 'webpack/buildin/amd-define' {
  declare module.exports: any;
}

declare module 'webpack/buildin/amd-options' {
  declare module.exports: any;
}

declare module 'webpack/buildin/global' {
  declare module.exports: any;
}

declare module 'webpack/buildin/module' {
  declare module.exports: any;
}

declare module 'webpack/buildin/return-require' {
  declare module.exports: any;
}

declare module 'webpack/hot/dev-server' {
  declare module.exports: any;
}

declare module 'webpack/hot/emitter' {
  declare module.exports: any;
}

declare module 'webpack/hot/log-apply-result' {
  declare module.exports: any;
}

declare module 'webpack/hot/only-dev-server' {
  declare module.exports: any;
}

declare module 'webpack/hot/poll' {
  declare module.exports: any;
}

declare module 'webpack/hot/signal' {
  declare module.exports: any;
}

declare module 'webpack/lib/AbstractPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/AmdMainTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/APIPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/ArrayMap' {
  declare module.exports: any;
}

declare module 'webpack/lib/AsyncDependenciesBlock' {
  declare module.exports: any;
}

declare module 'webpack/lib/AutomaticPrefetchPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/BannerPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/BasicEvaluatedExpression' {
  declare module.exports: any;
}

declare module 'webpack/lib/CachePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/CaseSensitiveModulesWarning' {
  declare module.exports: any;
}

declare module 'webpack/lib/Chunk' {
  declare module.exports: any;
}

declare module 'webpack/lib/ChunkRenderError' {
  declare module.exports: any;
}

declare module 'webpack/lib/ChunkTemplate' {
  declare module.exports: any;
}

declare module 'webpack/lib/CommonJsHarmonyMainTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/compareLocations' {
  declare module.exports: any;
}

declare module 'webpack/lib/CompatibilityPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/Compilation' {
  declare module.exports: any;
}

declare module 'webpack/lib/Compiler' {
  declare module.exports: any;
}

declare module 'webpack/lib/ConstPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/ContextModule' {
  declare module.exports: any;
}

declare module 'webpack/lib/ContextModuleFactory' {
  declare module.exports: any;
}

declare module 'webpack/lib/ContextReplacementPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/DefinePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/DelegatedModule' {
  declare module.exports: any;
}

declare module 'webpack/lib/DelegatedModuleFactoryPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/DelegatedPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/AMDDefineDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/AMDDefineDependencyParserPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/AMDPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/AMDRequireArrayDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/AMDRequireContextDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/AMDRequireDependenciesBlock' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/AMDRequireDependenciesBlockParserPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/AMDRequireDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/AMDRequireItemDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/CommonJsPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/CommonJsRequireContextDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/CommonJsRequireDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/CommonJsRequireDependencyParserPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/ConstDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/ContextDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/ContextDependencyHelpers' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/ContextDependencyTemplateAsId' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/ContextDependencyTemplateAsRequireCall' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/ContextElementDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/CriticalDependencyWarning' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/DelegatedSourceDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/DepBlockHelpers' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/DllEntryDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/getFunctionExpression' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/HarmonyAcceptDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/HarmonyAcceptImportDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/HarmonyExportDependencyParserPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/HarmonyExportExpressionDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/HarmonyExportHeaderDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/HarmonyExportSpecifierDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/HarmonyImportDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/HarmonyImportDependencyParserPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/HarmonyImportSpecifierDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/HarmonyModulesHelpers' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/HarmonyModulesPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/LoaderDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/LoaderPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/LocalModule' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/LocalModuleDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/LocalModulesHelpers' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/ModuleDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/ModuleDependencyTemplateAsId' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/ModuleDependencyTemplateAsRequireId' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/ModuleHotAcceptDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/ModuleHotDeclineDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/MultiEntryDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/NullDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/NullDependencyTemplate' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/PrefetchDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireContextDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireContextDependencyParserPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireContextPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireEnsureDependenciesBlock' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireEnsureDependenciesBlockParserPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireEnsureDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireEnsureItemDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireEnsurePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireHeaderDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireIncludeDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireIncludeDependencyParserPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireIncludePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireResolveContextDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireResolveDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireResolveDependencyParserPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/RequireResolveHeaderDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/SingleEntryDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/SystemImportContextDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/SystemImportDependenciesBlock' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/SystemImportDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/SystemImportParserPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/SystemPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/TemplateArgumentDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/UnsupportedDependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/dependencies/WebpackMissingModule' {
  declare module.exports: any;
}

declare module 'webpack/lib/DependenciesBlock' {
  declare module.exports: any;
}

declare module 'webpack/lib/DependenciesBlockVariable' {
  declare module.exports: any;
}

declare module 'webpack/lib/Dependency' {
  declare module.exports: any;
}

declare module 'webpack/lib/DllEntryPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/DllModule' {
  declare module.exports: any;
}

declare module 'webpack/lib/DllModuleFactory' {
  declare module.exports: any;
}

declare module 'webpack/lib/DllPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/DllReferencePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/EntryModuleNotFoundError' {
  declare module.exports: any;
}

declare module 'webpack/lib/EntryOptionPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/Entrypoint' {
  declare module.exports: any;
}

declare module 'webpack/lib/EnvironmentPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/EvalDevToolModulePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/EvalDevToolModuleTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/EvalSourceMapDevToolModuleTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/EvalSourceMapDevToolPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/ExtendedAPIPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/ExternalModule' {
  declare module.exports: any;
}

declare module 'webpack/lib/ExternalModuleFactoryPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/ExternalsPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/FlagDependencyExportsPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/FlagDependencyUsagePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/FlagInitialModulesAsUsedPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/FunctionModulePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/FunctionModuleTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/HashedModuleIdsPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/HotModuleReplacement.runtime' {
  declare module.exports: any;
}

declare module 'webpack/lib/HotModuleReplacementPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/HotUpdateChunkTemplate' {
  declare module.exports: any;
}

declare module 'webpack/lib/IgnorePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/JsonpChunkTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/JsonpExportMainTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/JsonpHotUpdateChunkTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/JsonpMainTemplate.runtime' {
  declare module.exports: any;
}

declare module 'webpack/lib/JsonpMainTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/JsonpTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/LibManifestPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/LibraryTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/LoaderOptionsPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/LoaderTargetPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/MainTemplate' {
  declare module.exports: any;
}

declare module 'webpack/lib/MemoryOutputFileSystem' {
  declare module.exports: any;
}

declare module 'webpack/lib/Module' {
  declare module.exports: any;
}

declare module 'webpack/lib/ModuleBuildError' {
  declare module.exports: any;
}

declare module 'webpack/lib/ModuleDependencyWarning' {
  declare module.exports: any;
}

declare module 'webpack/lib/ModuleError' {
  declare module.exports: any;
}

declare module 'webpack/lib/ModuleFilenameHelpers' {
  declare module.exports: any;
}

declare module 'webpack/lib/ModuleNotFoundError' {
  declare module.exports: any;
}

declare module 'webpack/lib/ModuleParseError' {
  declare module.exports: any;
}

declare module 'webpack/lib/ModuleParserHelpers' {
  declare module.exports: any;
}

declare module 'webpack/lib/ModuleReason' {
  declare module.exports: any;
}

declare module 'webpack/lib/ModuleTemplate' {
  declare module.exports: any;
}

declare module 'webpack/lib/ModuleWarning' {
  declare module.exports: any;
}

declare module 'webpack/lib/MovedToPluginWarningPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/MultiCompiler' {
  declare module.exports: any;
}

declare module 'webpack/lib/MultiEntryPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/MultiModule' {
  declare module.exports: any;
}

declare module 'webpack/lib/MultiModuleFactory' {
  declare module.exports: any;
}

declare module 'webpack/lib/NamedModulesPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/NewWatchingPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/node/NodeChunkTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/node/NodeEnvironmentPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/node/NodeHotUpdateChunkTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/node/NodeMainTemplate.runtime' {
  declare module.exports: any;
}

declare module 'webpack/lib/node/NodeMainTemplateAsync.runtime' {
  declare module.exports: any;
}

declare module 'webpack/lib/node/NodeMainTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/node/NodeOutputFileSystem' {
  declare module.exports: any;
}

declare module 'webpack/lib/node/NodeSourcePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/node/NodeTargetPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/node/NodeTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/node/NodeWatchFileSystem' {
  declare module.exports: any;
}

declare module 'webpack/lib/NodeStuffPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/NoErrorsPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/NormalModule' {
  declare module.exports: any;
}

declare module 'webpack/lib/NormalModuleFactory' {
  declare module.exports: any;
}

declare module 'webpack/lib/NormalModuleReplacementPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/NullFactory' {
  declare module.exports: any;
}

declare module 'webpack/lib/optimize/AggressiveMergingPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/optimize/AggressiveSplittingPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/optimize/ChunkModuleIdRangePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/optimize/CommonsChunkPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/optimize/DedupePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/optimize/EnsureChunkConditionsPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/optimize/FlagIncludedChunksPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/optimize/LimitChunkCountPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/optimize/MergeDuplicateChunksPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/optimize/MinChunkSizePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/optimize/OccurrenceOrderPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/optimize/RemoveEmptyChunksPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/optimize/RemoveParentModulesPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/optimize/UglifyJsPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/OptionsApply' {
  declare module.exports: any;
}

declare module 'webpack/lib/OptionsDefaulter' {
  declare module.exports: any;
}

declare module 'webpack/lib/Parser' {
  declare module.exports: any;
}

declare module 'webpack/lib/PrefetchPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/ProgressPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/ProvidePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/RawModule' {
  declare module.exports: any;
}

declare module 'webpack/lib/RecordIdsPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/removeAndDo' {
  declare module.exports: any;
}

declare module 'webpack/lib/RequestShortener' {
  declare module.exports: any;
}

declare module 'webpack/lib/RequireJsStuffPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/RuleSet' {
  declare module.exports: any;
}

declare module 'webpack/lib/SetVarMainTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/SingleEntryPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/SourceMapDevToolModuleOptionsPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/SourceMapDevToolPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/Stats' {
  declare module.exports: any;
}

declare module 'webpack/lib/Template' {
  declare module.exports: any;
}

declare module 'webpack/lib/TemplatedPathPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/UmdMainTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/UnsupportedFeatureWarning' {
  declare module.exports: any;
}

declare module 'webpack/lib/UseStrictPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/validateWebpackOptions' {
  declare module.exports: any;
}

declare module 'webpack/lib/WarnCaseSensitiveModulesPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/WatchIgnorePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/web/WebEnvironmentPlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/webpack' {
  declare module.exports: any;
}

declare module 'webpack/lib/webpack.web' {
  declare module.exports: any;
}

declare module 'webpack/lib/WebpackOptionsApply' {
  declare module.exports: any;
}

declare module 'webpack/lib/WebpackOptionsDefaulter' {
  declare module.exports: any;
}

declare module 'webpack/lib/WebpackOptionsValidationError' {
  declare module.exports: any;
}

declare module 'webpack/lib/webworker/WebWorkerChunkTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/webworker/WebWorkerHotUpdateChunkTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/webworker/WebWorkerMainTemplate.runtime' {
  declare module.exports: any;
}

declare module 'webpack/lib/webworker/WebWorkerMainTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/lib/webworker/WebWorkerTemplatePlugin' {
  declare module.exports: any;
}

declare module 'webpack/web_modules/node-libs-browser' {
  declare module.exports: any;
}

